### ISSUE TITLE
Problems with using Pokemon system

### ISSUE THREAD

**Issue by Monsterlax** [phantomindex/PokemonSystem#1]
Dear phantomindex,

I am a new twitch streamer and i am currently running the PhantomBot 2.3.2.

I am interested in using the pokemon system game within my twitch stream.
However when i add the files in the correct area 
"pokemonSystem.js should be in scripts>games folder

games-pokemonSystem.js should be in scripts>lang>english>games folder"

The commands do not register in my control panel or when i type !pokemon in chat.

It does show in my modules and it is enabled.

I have tried completely downloading a new PhantomBot and trying to see if it would work with default system information, and it still had the same results. I will include screenshots with this message.

Can you help me figure this out?
If you need any more information let me know.

scripts>games folder 
![image](https://cloud.githubusercontent.com/assets/22845261/19402639/17a832b8-9230-11e6-93a6-931a0d7f0b5e.png)

scripts>lang>english>games folder
![image](https://cloud.githubusercontent.com/assets/22845261/19402654/35782794-9230-11e6-9728-62c5378f40f3.png)

Enabled under modules
![image](https://cloud.githubusercontent.com/assets/22845261/19402663/4741480c-9230-11e6-9244-0064fb840892.png)

![image](https://cloud.githubusercontent.com/assets/22845261/19402677/5f36d1d4-9230-11e6-9420-f3cfcad40c96.png)

and games section 
![image](https://cloud.githubusercontent.com/assets/22845261/19402685/6e0585e8-9230-11e6-9a5f-1d19c7607880.png)

Thank you in advance
Monsterlax

**Comment by phantomindex** [comment]
Have you tried it on a fresh save?

**Comment by Monsterlax** [comment]
Yeah i redownloaded the complete bot besides the login info

**Comment by Monsterlax** [comment]
which was why everything was disabled

**Comment by phantomindex** [comment]
All I can think of is re downloading the script. Does the console show anything when you mess with the commands? Have you tried !pokeballgo

**Comment by Monsterlax** [comment]
nothing when i type that.
no feed back no nothing. I have redownloaded the scripts a few times as well with no solutions. 

the picture above shows what happens after i type !pokemon, same thing happens with help or go or any of the commands

**Comment by phantomindex** [comment]
Thats, so odd.. try moving the files to commands instead of games. If that doesn't work, I will need to look into it when I get back from work tonight.

**Comment by Monsterlax** [comment]
I did that as well, did that with every container
which was one of the reasons i reset the bot completely when you released the new version 
because under modules it still had the pokemon in every box, from all the attempts.

But even with a brand new it didnt work. not sure why.

Please do when you get back, i can screenshare if need be

Thank you again

**Comment by phantomindex** [comment]
Wait
 I know what it is. Open pokemonesystem.js with notepad++ scroll all the way down and change Al the paths with commands to games.

**Comment by Monsterlax** [comment]
seems to be working thank you

**Comment by phantomindex** [comment]
I just updated it on the source, so no one else will have this issue
