### ISSUE TITLE
Problems with downloading the update

### ISSUE THREAD

**Issue by Monsterlax** [phantomindex/PokemonSystem#3]
I tried to update the pokemon game and i started to receive a lot of errors for missing files etc.
The files are in the correct folder. I also re downloaded the files as well as updated my bot to the latest version.

In the command line:
![image](https://cloud.githubusercontent.com/assets/22845261/21031138/f038f58a-bd6f-11e6-8c6c-c1c992ebbbab.png)

for these commands:
![image](https://cloud.githubusercontent.com/assets/22845261/21031146/fd53c42a-bd6f-11e6-93a6-6854449ed96a.png)

scripts->games 
![image](https://cloud.githubusercontent.com/assets/22845261/21031195/332d78ca-bd70-11e6-9a56-6d15e1e848a6.png)

scripts->lang...->games
![image](https://cloud.githubusercontent.com/assets/22845261/21031201/411fd23e-bd70-11e6-8d17-bb90e0802bb7.png)

Please let me know if you can find a solution thank you 
MonsterLax

**Comment by phantomindex** [comment]
Tryaking a new text file in notepad and cppy and paste from my github to
them and rename them

Never Save As.. from the github page, because it saves in a baf format

**Comment by Monsterlax** [comment]
They are all saved as .js. i downloaded the zip and then moved them in 
![image](https://cloud.githubusercontent.com/assets/22845261/21034692/ad08d1a0-bd87-11e6-8fae-8a7cb216af32.png)

**Comment by Monsterlax** [comment]
just re-downloaded everything  and i still get the same issue whenever i enable the pokemon system under modules

**Comment by Monsterlax** [comment]
Just tried again with a brand new download again and tried messing with the files, and looking at the other modules. I am not sure what is going wrong or how to fix it

**Comment by phantomindex** [comment]
Try in the costum modules directory on github for phantombot

**Comment by Monsterlax** [comment]
I did try that, I tried moving it into every folder and nothing worked.
I also tried downloading a new bot and only keeping my bot login. Still nothing worked.
It still will not read the file.

If you get a chance can you try to do it on a new bot and see if you get the same errors.

**Comment by phantomindex** [comment]
https://github.com/phantomindex/custom-modules

**Comment by Monsterlax** [comment]
That seems to have fixed the problem thank you.

I appreciate it

**Comment by phantomindex** [comment]
Yep
